apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.posts, name='index'),
    path('<int:post_id>/', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/comment/', views.comment, name='comment'),
    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/dislike/', views.dislike, name='dislike'),
    path('<int:post_id>/comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    path('<int:post_id>/comment/<int:comment_id>/dislike/', views.like_comment, name='dislike_comment'),
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('<int:post_id>/redact/', views.redact_post, name='redact_post')
]

apps/catalog/urls.py
from django.urls import path

from . import views
from .views import CataloglistView, ProductByCategoryView, ProductDetailView, CartListView

app_name = 'catalog'

urlpatterns = [
    path('', CataloglistView.as_view(), name='index'),
    path('cart', CartListView.as_view(), name='cart'),
    path('<str:product_id>/add/', ProductByCategoryView.addToCart, name='add'),
    path('<str:category_id>', ProductByCategoryView.as_view() , name='category'),
    path('products/<str:product_id>', ProductDetailView.as_view(), name='product'),
    path('<str:cart_id>/order/<str:order_id>/increment/', CartListView.increment, name='increment'),
    path('<str:cart_id>/order/<str:order_id>/decrement/', CartListView.decrement, name='decrement'),
    path('<str:cart_id>/order/<str:order_id>/delete/', CartListView.deleteOrder, name='delete')
]

apps/main/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
app_name = 'main'
urlpatterns = [
    path('', views.index, name= 'index'),
    # path('lol', views.index, name='about'),
    path('about', views.index, name='about'),
    path('for_us', views.index, name='for_us'),
    path('contacts', views.index, name='contacts'),
    path('veterinarsadvive', views.index, name='veterinarsadvice'),
    path('article', views.index, name='blog/index')
]

apps/members/urls.py
from django.urls import path
from .views import *

app_name = 'members'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('profile/', profile_view, name='profile'),
    ] 

cor/urls.py
from django.urls import path, include

"""
URL configuration for cor project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('members/', include('apps.members.urls', namespace='members')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include

"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('catalog/', include('apps.catalog.urls', namespace='catalog')),
    path('members/', include('apps.members.urls', namespace='members')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include_block/_breadcrumbs.html
<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{% url 'main:index' %}"><i class="fas fa-home me-1"></i>Home</a>
      </li>

      {% for url, name in breadcrumbs.items %}

      {% if url == 'current' %}
        <li class="breadcrumb-item">
            <a>{{name}}</a>
        </li>
      {% else %}
      <li class="breadcrumb-item active">
        <a href="{{url}}">{{name}}</a>
         </li>
      {% endif %}
        
    {% endfor %}
    </ol>
  </nav>

templates/include_block/_main_navbar.html
<a class="btn btn-outline-primary btn-sm" href="{% url 'admin:index' %}">Admin</a>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
      <a class="navbar-brand" href="{% url 'main:index' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shop-window" viewBox="0 0 20 20">
          <path d="M2.97 1.35A1 1 0 0 1 3.73 1h8.54a1 1 0 0 1 .76.35l2.609 3.044A1.5 1.5 0 0 1 16 5.37v.255a2.375 2.375 0 0 1-4.25 1.458A2.37 2.37 0 0 1 9.875 8 2.37 2.37 0 0 1 8 7.083 2.37 2.37 0 0 1 6.125 8a2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.625V5.37a1.5 1.5 0 0 1 .361-.976zm1.78 4.275a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 1 0 2.75 0V5.37a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.255a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0M1.5 8.5A.5.5 0 0 1 2 9v6h12V9a.5.5 0 0 1 1 0v6h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1V9a.5.5 0 0 1 .5-.5m2 .5a.5.5 0 0 1 .5.5V13h8V9.5a.5.5 0 0 1 1 0V13a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V9.5a.5.5 0 0 1 .5-.5"/>
        </svg>PetShop
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}">Блог</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'catalog:index' %}">Категорії</a>
          </li>


<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="{% url 'main:for_us' %}">О нас</a>-->
<!--          </li>-->

<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="{% url 'main:veterinarsadvice' %}">Ветеринарские советы</a>-->
<!--          </li>-->

<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="{% url 'main:contacts' %}">Контакты</a>-->
<!--          </li>-->

<!--          <li class="nav-item">-->
<!--            <a class="nav-link" href="{% url 'main:about' %}">Про сайт</a>-->
<!--          </li>-->



        </ul>
        <div class="d-flex gap-2">
          {% if user.is_authenticated %}
            <a class="btn btn-outline-primary btn-sm" href="{% url 'members:logout' %}">Вийти</a>
            <a class="btn btn-primary btn-sm " href="{% url 'members:profile' %}">Профіль</a>

            {% else %}
            <a class="btn btn-outline-primary btn-sm" href="{% url 'members:login' %}">Увійти</a>
            <a class="btn btn-outline-warning btn-sm" href="{% url 'members:signup' %}">Зареєструватися</a>
          {% endif %}
          <style>
                .cart-button {
                    background-color: dodgerblue;
                    cursor: pointer;
                    border-color: #2C3E4C;
                    border-style: solid;
                    border-radius: 5px;
                    padding: 4px;
                    margin-left: 2px;
                    margin-right: 2px;
                    transition: padding 1s, background-color 1s,
                    border-color 1s, border-radius 1s;
                }

                .cart-button:hover {
                    background-color: #FF0000;
                    border-color: #FF0000;
                    border-radius: 5px;
                    padding: 4px;
                    margin-left: 2px;
                    margin-right: 2px;
                    transition: padding 1s, background-color 1s,
                    border-color 1s, border-radius 1s;
                }
        </style>
        <div class="content">
             <a class="nav-link" href="{% url 'catalog:cart' %}">
              <button class="cart-button">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-basket3-fill" viewBox="0 0 16 16">
                  <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM2.468 15.426.943 9h14.114l-1.525 6.426a.75.75 0 0 1-.729.574H3.197a.75.75 0 0 1-.73-.574z"/>
                </svg>
              </button>
            </a>
        </div>
      </div>
      </div>
    </div>
  </nav>