apps/catalog/urls.py
from django.urls import path

from . import views
from .views import CataloglistView, ProductByCategoryView, ProductDetailView, CartListView

app_name = 'catalog'

urlpatterns = [
    path('', CataloglistView.as_view(), name='index'),
    path('cart', CartListView.as_view(), name='cart'),
    path('<str:product_id>/add/', ProductByCategoryView.addToCart, name='add'),
    path('<str:category_id>', ProductByCategoryView.as_view() , name='category'),
    path('products/<str:product_id>', ProductDetailView.as_view(), name='product'),
    path('<str:cart_id>/order/<str:order_id>/increment/', CartListView.increment, name='increment'),
    path('<str:cart_id>/order/<str:order_id>/decrement/', CartListView.decrement, name='decrement'),
    path('<str:cart_id>/order/<str:order_id>/delete/', CartListView.deleteOrder, name='delete')
]

cor/urls.py
from django.urls import path, include

"""
URL configuration for cor project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('members/', include('apps.members.urls', namespace='members')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include

"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('catalog/', include('apps.catalog.urls', namespace='catalog')),
    path('members/', include('apps.members.urls', namespace='members')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/catalog/views.py
from datetime import timezone, datetime
from multiprocessing import context
from os import path

import requests
from django.db.models import Sum
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse

from apps.main.mixins import ListViewBreadcrumbMixin, DetailViewBreadcrumbMixin
from .models import Catalog, Product, CategoryDTO, ProductDTO, Cart, Order


# import Q

# Create your views here.

class CataloglistView(ListViewBreadcrumbMixin):
    model = Catalog
    template_name = 'catalog/index.html'
    context_object_name = 'categories'

    def get_new_offers(self):
        url = 'https://prod.salesbox.me/api/v4/companies/barnipet/offers/get-new-offers?lang=uk'
        response = requests.get(url)
        products = response.json()['data']
        dtos = []
        for product in products:
            dtos.append(ProductDTO.from_dict(product))
        return dtos

    def get_queryset(self):
        return Catalog.objects.order_by('order')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['offers'] = self.get_new_offers()
        return context

    def get_breradcrumb(self):
        self.breadcrumbs = {
            'current': 'Каталог',
        }
        return self.breadcrumbs


class ProductByCategoryView(ListViewBreadcrumbMixin):
    model = Catalog
    template_name = 'catalog/product_by_category.html'
    context_object_name = 'category'

    def get_product_list(self, categoryId, internalCategoryId):
        # url = 'https://prod.salesbox.me/api/v4/companies/barnipet/offers/filter?page=1&pageSize=20&categoryId={}'.format(categoryId)
        url = f'https://prod.salesbox.me/api/v4/companies/barnipet/offers/filter?page=1&pageSize=20&categoryInternalId={internalCategoryId}&categoryId={categoryId}&lang=uk'
        response = requests.get(url)
        data = response.json()
        return data
    def get_product_by_id(productId):
        url = f'https://prod.salesbox.me/api/v4/companies/barnipet/offers/{productId}'
        response = requests.get(url)
        payload = response.json()['data']
        return ProductDTO.from_dict(payload)

    def get_current_category(self, categoryId):
        model = Catalog.objects.get(id=categoryId)
        return CategoryDTO.from_dict(model.__dict__)

    def getCategories(self):
        categories = []
        for category in Catalog.objects.order_by("order"):
            categories.append(CategoryDTO.from_dict(category.__dict__))
        return categories


    def get_queryset(self):
        categoryId = self.kwargs['category_id']
        self.categories = self.getCategories()
        self.category = self.get_current_category(categoryId)
        products = self.get_product_list(categoryId, self.category.get_internal_id())['data']
        dtos = []
        for product in products:
            dtos.append(ProductDTO.from_dict(product))

        print(products)
        return dtos

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = self.categories
        context['category'] = self.category
        return context

    def get_breradcrumb(self):
        self.breadcrumbs = {
            'current': self.category.name,
        }
        return self.breadcrumbs

    def addToCart(request, product_id):
        session_id = request.session.session_key
        print(session_id)

        if session_id is None:
            raise Exception("No active session")
        cart = None
        try:
            cart = Cart.objects.get(id=session_id)
        except Cart.DoesNotExist:
            cart = Cart.objects.create(id=session_id)

        try:
            order_query = Order.objects.get(productId=product_id, cart=cart)
            order = order_query.__dict__
            order_id = order['id']
            quantity = order['quantity']
            Order.objects.filter(id=order_id).update(quantity=quantity + 1, updated=datetime.now())
        except Order.DoesNotExist:
            orderDTO = ProductByCategoryView.get_product_by_id(productId=product_id)
            order = Order(productId=product_id, name=orderDTO.name, price=orderDTO.price, previewURL=orderDTO.previewURL, quantity=1, created=datetime.now(), updated=datetime.now(), cart=cart)
            Order.save(order)
        return HttpResponseRedirect("catalog")

class ProductDetailView(ListViewBreadcrumbMixin):
    model = Product
    template_name = 'catalog/product.html'
    context_object_name = 'product'
    
    def get_breradcrumb(self):
        breadcrumbs = { reverse('catalog:index'): 'Каталог' }
        return breadcrumbs

    def get_product_by_id(self, product_id):
        url = f'https://prod.salesbox.me/api/v4/companies/barnipet/offers/{product_id}?lang=uk'
        response = requests.get(url)
        data = response.json()['data']
        if data is not None:
            return ProductDTO.from_dict(data)
        return None
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = self.get_product_by_id(self.kwargs['product_id'])
        return context


class CartListView(ListViewBreadcrumbMixin):
    # model = Cart
    template_name = 'catalog/cart.html'
    context_object_name = 'cart'

    def get_queryset(self):
        return self.find_of_create_cart()

    def get_breradcrumb(self):
        breadcrumbs = {reverse('catalog:index'): 'Каталог'}
        return breadcrumbs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = self.find_of_create_cart()
        context['cart'] = cart

        orders = Order.objects.filter(cart=cart)
        context['orders'] = orders

        total = 0
        for order in orders:
            total += order.get_cost()

        context['total'] = total
        return context

    def find_of_create_cart(self):
        session_id = self.request.session.session_key
        print(session_id)

        if session_id is None:
            raise Exception("No active session")

        try:
            return Cart.objects.get(id=session_id)
        except Cart.DoesNotExist:
            print("cart does not exist")
            print("Creating new cart")
            return Cart.objects.create(id=session_id)

    def decrement(request, cart_id, order_id):
        quantity = Order.objects.get(id=order_id).__dict__['quantity']
        if quantity == 1:
            Order.objects.get(id=order_id).delete()
        else:
            Order.objects.filter(id=order_id).update(quantity=quantity - 1)

        return HttpResponseRedirect("/catalog/cart")

    def increment(request, cart_id, order_id):
        quantity = Order.objects.get(id=order_id).__dict__['quantity']
        Order.objects.filter(id=order_id).update(quantity=quantity + 1)

        return HttpResponseRedirect("/catalog/cart")

    def deleteOrder(request, cart_id, order_id):
        order = Order.objects.get(id=order_id)
        order.delete()
        return HttpResponseRedirect("/catalog/cart")


    # return HttpResponseRedirect("/catalog/cart")

apps/catalog/templates/catalog/cart.html
{% extends 'base.html' %}

{% block title %}Кошик{% endblock %}


{% block content %}

<h5>У Вашій корзині товарів: {{ orders.count }}</h5>

<h6>Всього: {{ total }} грн</h6>
<p>
    <button class="btn btn-primary" type="button">Оформити заказ</button>
</p>

{% if orders %}
<ul class="list-group">
    <li class="list-group-item">
        <div class="container">
            <div class="row">
                <div class="col col-lg-1">
                </div>
                <div class="col col-lg-5">
                    Назва
                </div>
                <div class="col col-lg-1">
                    Ціна
                </div>
                <div class="col col-lg-1">
                    Зменшити
                </div>
                <div class="col col-lg-1">
                    Кількість
                </div>
                <div class="col col-lg-1">
                    Збільшити
                </div>
                <div class="col col-lg-1">
                    Вартість
                </div>
                <div class="col col-lg-1">
                    Видалити
                </div>
            </div>
        </div>
    </li>
    {% for order in orders %}
    <li class="list-group-item">
        <div class="container">
            <div class="row">
                <div class="col col-lg-1">
                    <img alt="Responsive image" class="img-fluid" src='{{ order.previewURL }}'>
                </div>
                <div class="col col-lg-5">
                    {{ order.name }}
                </div>
                <div class="col col-lg-1">
                    {{ order.price }}
                </div>
                <div class="col col-lg-1">
                    <button type="button" class="btn btn-warning" onclick="decrement('{{ order.id }}')" id="btn_decrement_{{comment.id}}">-</button>
                </div>
                <div class="col col-lg-1">
                    <p>{{ order.quantity }}</p>
                </div>
                <div class="col col-lg-1">
                    <button type="button" class="btn btn-success" onclick="increment('{{ order.id }}')" id="btn_increment_{{comment.id}}">+</button>
                </div>
                <div class="col col-lg-1">
                    <p>{{ order.get_cost }}</p>
                </div>
                <div class="col col-lg-1">
                    <button type="button" class="btn btn-danger" onclick="deleteOrder('{{ order.id }}')" id="btn_delete_{{comment.id}}">Видалити</button>
                </div>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Товаров нет</p>
{% endif %}

<script>
    function increment(order_id){
        fetch('{% url "catalog:increment" cart.id 0 %}'.replace('0', order_id))
        .then(data => {
            console.log(data)
            window.location.reload();
        })
        .catch(error => console.log(error));
    }

    function decrement(order_id){
        fetch('{% url "catalog:decrement" cart.id 0 %}'.replace('0', order_id))
        .then(data => {
            console.log(data)
            window.location.reload();
        })
        .catch(error => console.log(error));
    }

    function deleteOrder(order_id){
        fetch('{% url "catalog:delete" cart.id 0 %}'.replace('0', order_id))
                .then(data => {
                    console.log(data)
                    window.location.reload();
                })
                .catch(error => console.log(error));
    }
</script>


{% endblock %}

apps/catalog/templates/catalog/index.html
{% extends 'base.html' %}

{% block title %}Каталог{% endblock %}


{% block content %}
<div class="mt-3 rounded-3 bg-body-tertiary p-4">
    <h3>Категорії</h3>
    <h6>{{ categories.count }} категорій</h6>
    {% if object_list %}
    <div class='row mt-4'>
        {% for category in object_list %}
        <div class='col-2'>
            <div class='card'>
                {% if category.has_image %}
                <img alt='{{ category.name }}' class='card-img-top' src='{{ category.previewURL }}'>
                {% else %}
                <img alt='{{ category.name }}' class='card-img-top' src='https://via.placeholder.com/300x200'>
                {% endif %}
                <div class='card-body'>
                    <div class="align: center">
                        <h5 class='card-title'>{{ category.name }}</h5>
                    </div>
                </div>
                <a class='btn btn-primary' href='{{ category.get_absolute_url }}'>Переглянути</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>Категорій немає</p>
    {% endif %}
</div>

<div class="mt-3 rounded-3 bg-body-tertiary p-4">
    <h3>Останні надходження</h3>
    <h6>{{ id.count }}</h6>
    {% if object_list %}
    <div class='row mt-4'>
        {% for product in offers %}
        <div class='col-4'>
            <div class='card'>
                {% if product.previewURL %}
                <a href="product.html">
                    <img alt='{{ product.name }}' class='card-img-top' src='{{ product.previewURL }}'>
                </a>
                {% else %}
                <img alt='{{ product.name }}' class='card-img-top' src='https://via.placeholder.com/300x200'>
                {% endif %}
                <div class='card-body'>
                    <h5 class='card-title'>{{ product.get_name }}</h5>
                    <h6>Ціна: {{ product.price }} грн</h6>
                    <div class="container">
                        <div aria-label="Панель инструментов с группами кнопок" class="btn-toolbar justify-content-end" role="toolbar">
                            <div aria-label="Перегляд" class="btn-group me-2" role="group">
                                <a href='{{ product.get_absolute_url }}' class="btn btn-info" role="button">
                                    <svg class="bi bi-eye" fill="currentColor" height="16" viewBox="0 0 16 16"
                                         width="16" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                                        <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                                    </svg>
                                </a>
                            </div>
                            <div aria-label="Придбати" class="btn-group me-2" role="group">
                                <button type="button" class="btn btn-success" onclick="addToCart('{{ product.id }}')">
                                    <svg class="bi bi-cart4" fill="currentColor" height="16" viewBox="0 0 16 16"
                                         width="16" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
                                    </svg>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>Товарів немає</p>
    {% endif %}
</div>

<script>
    function addToCart(product_id){
        fetch('{% url "catalog:add" 0 %}'.replace('0', product_id))
        .then(data => {
            console.log(data)
            // window.location.reload();
        })
        .catch(error => console.log(error));
    }
</script>

{% endblock %}

apps/catalog/templates/catalog/product.html
{% extends 'base.html' %}

{% block title %}Каталог{% endblock %}



{% block content %}
    

    <div class="mt-3 rounded-3 bg-body-tertiary p-4">
        <h3>{{ product.get_name }}</h3>
        <div class='row mt-4'>
            <div class="col-4">
                <img src='{{ product.previewURL }}' class='card-img-top' alt='{{ product.get_name }}'>
            </div>
            <div class="col-8">
                <p>Ціна: {{ product.price }} грн</p>
<!--                <p>Категорія: {{ product.category }}</p>-->
                <p>{{ product.description }}</p>


                <div aria-label="Придбати" class="btn-group me-2" role="group">
                    <button type="button" class="btn btn-success" onclick="addToCart('{{ product.id }}')">
                                    <svg class="bi bi-cart4" fill="currentColor" height="16" viewBox="0 0 16 16"
                                         width="16" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
                                    </svg>
                    </button>
                </div>
                <script>
                    function addToCart(product_id){
                        fetch('{% url "catalog:add" 0 %}'.replace('0', product_id))
                        .then(data => {
                            console.log(data)
                            // window.location.reload();
                        })
                        .catch(error => console.log(error));
                    }
                </script>

<!--                <style>-->
<!--                    .add-to-cart {-->
<!--                        background-color: #3399ff;-->
<!--                        color: #FFFFFF;-->
<!--                        border-color: #3399ff;-->
<!--                        border-radius: 7px;-->
<!--                        padding: 5px;-->

<!--                    }-->
<!--                </style>-->
<!--                <button class="add-to-cart">-->
<!--                    Додати до кошику-->
<!--                </button>-->
            </div>
        </div> 

    </div>
{% endblock %}

apps/catalog/templates/catalog/product_by_category.html
{% extends 'base.html' %}

{% block title %}Каталог{% endblock %}



{% block content %}
    

        <div class="mt-3 rounded-3 bg-body-tertiary p-4">
<!--                <div class='row mt-4'>-->
<!--                    {% for categor in categories %}-->
<!--                        <div class='col-3 col-sm-3 col-md-1'>-->
<!--                            <a href='{{ categor.get_absolute_url }}'>-->
<!--                            <div class='card p-0'>-->
<!--                                {% if categor.image %}-->
<!--                                    <img src='{{ categor.image.url }}' class='card-img-top' alt='{{ product.name }}'>-->
<!--                                {% else %}-->
<!--                                    <img src='https://via.placeholder.com/300x200' class='card-img-top' alt='{{ product.name }}'>-->
<!--                                {% endif %}-->
<!--                                -->
<!--                                    <p style='font-size: 10px;' class='text-center'>{{ categor.name }}</p>-->
<!--                               -->
<!--                            </div>-->
<!--                            </a>-->
<!--                        </div>-->
<!--                    {% endfor %}-->
<!--                </div>-->

            {% if object_list %}
                <div class='row mt-4'>
                    {% for product in object_list %}
                        <div class='col-4'>
                            <div class='card'>
                                {% if product.has_image %}
                                    <img src='{{ product.previewURL}}' class='card-img-top' alt='{{ product.name }}'>
                                {% else %}
                                    <img src='https://via.placeholder.com/300x200' class='card-img-top' alt='{{ product.name }}'>
                                {% endif %}
                                <div class='card-body'>
                                    <h5 class='card-title'>{{ product.get_name }}</h5>
                                    <h6 class='card-title'>{{ product.price }} грн</h6>
                                </div>
                                <div class="container">
                                    <div aria-label="Панель инструментов с группами кнопок" class="btn-toolbar justify-content-end" role="toolbar">
                                        <div aria-label="Перегляд" class="btn-group me-2" role="group">
                                            <a href='{{ product.get_absolute_url }}' class="btn btn-info" role="button">
                                                <svg class="bi bi-eye" fill="currentColor" height="16" viewBox="0 0 16 16"
                                                     width="16" xmlns="http://www.w3.org/2000/svg">
                                                    <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z"/>
                                                    <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0"/>
                                                </svg>
                                            </a>
                                </div>
                                <div aria-label="Придбати" class="btn-group me-2" role="group">
                                    <button type="button" class="btn btn-success" onclick="addToCart('{{ product.id }}')">
                                        <svg class="bi bi-cart4" fill="currentColor" height="16" viewBox="0 0 16 16"
                                             width="16" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
                                        </svg>
                                    </button>
                                </div>
                        </div>
                    </div>

                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p>Товаров нет</p>
            {% endif %}
        </div>
        <script>
            function addToCart(product_id){
                fetch('{% url "catalog:add" 0 %}'.replace('0', product_id))
                .then(data => {
                    console.log(data)
                    // window.location.reload();
                })
                .catch(error => console.log(error));
            }
        </script>

{% endblock %}