apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.posts, name='index'),
    path('<int:post_id>/', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/comment/', views.comment, name='comment'),
    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/dislike/', views.dislike, name='dislike'),
    path('<int:post_id>/comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    path('<int:post_id>/comment/<int:comment_id>/dislike/', views.like_comment, name='dislike_comment'),
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('<int:post_id>/redact/', views.redact_post, name='redact_post')
]

cor/urls.py
from django.urls import path, include

"""
URL configuration for cor project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('members/', include('apps.members.urls', namespace='members')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include

"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('catalog/', include('apps.catalog.urls', namespace='catalog')),
    path('members/', include('apps.members.urls', namespace='members')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='posts', null=True, default=None)
    title = models.CharField(verbose_name='Заголовок', max_length=255)
    content = models.TextField(verbose_name='Контент')
    image = models.ImageField(verbose_name='Малюнок', upload_to='post_images/')
    is_published = models.BooleanField(verbose_name='Опубліковано', default=False, blank=True)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)
    dislikes = models.ManyToManyField(User, related_name='post_dislikes', blank=True)
    views = models.IntegerField(verbose_name='Перегляди', default=0, blank=True)
    created_at = models.DateTimeField(verbose_name='Дата створення', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Дата оновлення', auto_now=True)


    def __str__(self):
        return f'{self.title} - {self.created_at} - {self.is_published}'

    class Meta:  # Це потрібно для відображення моделі в адмінці
        verbose_name = 'Пост'
        verbose_name_plural = 'Пости'
        ordering = ['-created_at']


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост', related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='comments', null=True, default=None)
    content = models.TextField(verbose_name='Контент')
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)
    dislikes = models.ManyToManyField(User, related_name='comment_dislikes', blank=True)
    created_at = models.DateTimeField(verbose_name='Дата створення', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Дата оновлення', auto_now=True)

    def __str__(self):
        return f'{self.author} - {self.created_at}'

    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'
        ordering = ['created_at']

apps/blog/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'is_published', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'is_published': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'color_post': forms.CheckboxInput(attrs={'class': 'form-color'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control'})
        }

    

apps/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# Create your views here.
# @login_required
def index(request):
    posts = Post.objects.filter(is_published=True)
    create_form = PostForm()

    context = {
        'posts': posts,
        'form': create_form
    }

    return render(request, 'blog/index.html', context)


@login_required
def post(request, post_id):
    # post = Post.objects.get(id=post_id)
    form_comment = CommentForm()
    post = get_object_or_404(Post, id=post_id)
    post.views += 1
    post.save()
    context = {
        'post': post,
        'comment_form': form_comment,
    }

    return render(request, 'blog/post.html', context)

@login_required
def posts(request):
    posts = Post.objects.all()
    form_create_post = PostForm()
    context = {
        'posts': posts,
        'form_create_post': form_create_post
    }

    return render(request, 'blog/index.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, 'Пост створено')
    return redirect('blog:index')


@login_required
def comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            print(comment)
            comment.post = post
            comment.author = request.user
            comment.save()
            messages.success(request, 'Коментар додано')
    return redirect('blog:post', post_id=post_id)


@login_required
def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.likes.all():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    if request.user in post.dislikes.all():
        post.dislikes.remove(request.user)

    post.save()
    return JsonResponse({
        'dislikes': post.dislikes.count(),
        'likes': post.likes.count()})

@login_required
def dislike(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.dislikes.all():
        post.dislikes.remove(request.user)
    else:
        post.dislikes.add(request.user)

    if request.user in post.likes.all():
        post.likes.remove(request.user)

    post.save()
    return JsonResponse({
        'dislikes': post.dislikes.count(),
        'likes': post.likes.count()})


@login_required
def like_comment(request, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, post__id=post_id)
    if request.user in comment.likes.all():
        comment.likes.remove(request.user)
    else:
        comment.likes.add(request.user)
    comment.save()
    return JsonResponse({'likes': comment.likes.count()})

@login_required
def dislike_comment(request, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, post__id=post_id)
    if request.user in comment.dislikes.all():
        comment.dislikes.remove(request.user)
    else:
        comment.dislikes.add(request.user)
    comment.save()
    return JsonResponse({'dislikes': comment.dislikes.count()})


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)
    post.delete()
    messages.success(request, 'Пост видалено')
    return redirect('members:profile')

@login_required
def redact_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Пост змінено')
            return redirect('members:profile')
        else:
            messages.error(request, 'Форма має помилки. Будь ласка, виправте їх.')
    else:
        form = PostForm(instance=post)

    return redirect('members:profile')

@login_required
def change_color(request, post_id):
    post = get_object_or_404(Post, id=post_id)

apps/blog/templates/blog/edit_post.html
{% extends 'base.html' %}

{% block title %}Edit Post{% endblock %}



{% block content %}
    
        <div class="mt-3 rounded-3 bg-body-tertiary p-4">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn btn-primary">Зберегти</button>
            </form>
        </div>
       

{% endblock %}

apps/blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}



{% block content %}
    

        <div class="mt-3 rounded-3 bg-body-tertiary p-4">
            <h3>Блог</h3>
            <p>Кількість постів: {{ posts.all.count }}</p>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
               Створити пост
            </button>
            <hr class="my-4">
            <div class="row g-4">
                {% for post in posts %}
                    <div class="col-4">


                            <div class="card">
                                <a href="{% url 'blog:post' post.id %}" class="text-decoration-none text-white">
                                <img src="{{post.image.url}}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">{{post.title}}</h5>
                                    <p class="card-text">@{{post.author}}</p>
                                    <small class="text-muted">{{post.created_at|timesince}}</small>
                                    <!-- <div class="d-flex justify-content-between">
                                        <div class="d-flex align-items-center">
                                            <img src="https://via.placeholder.com/30" class="rounded-circle me-2" alt="...">
                                            <span>{{post.author}}</span>
                                        </div>
                                        <div>
                                            <span class="badge bg-secondary">{{post.category}}</span>
                                        </div>
                                    </div> -->
                                </div>
                            </a>
                                <div class="card-footer">
                                    <div class="d-flex justify-content-between text-center">
                                        <h5><span class="badge ">👁️ {{post.views}}</span></h5>
                                        <h5><span class="badge ">🗨️ {{post.comments.count}}</span></h5>
                                        <h5><span class="btn" id="btn_like_{{post.id}}" style="cursor: pointer;">👍 {{post.likes.count}}</span></h5>
                                        <h5><span class="btn" id="btn_dislike_{{post.id}}" style="cursor: pointer;">👎 {{post.dislikes.count}}</span></h5>
                                    </div>
                                </div>
                            </div>


                    </div>
                {% endfor %}


            </div>
        </div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Створити пост</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{% url 'blog:create' %}" method="post" enctype="multipart/form-data">

            <div class="modal-body">
                {% csrf_token %}
                {{ form_create_post }}
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Створити</button>

            </div>
        </form>
      </div>
    </div>
  </div>

  <script>

    function like(post_id){
        fetch('{% url "blog:like" 0 %}'.replace('0', post_id))
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_like_' + post_id).innerText = `👍 ${data.likes}`;
            document.getElementById('btn_dislike_' + post_id).innerText = `👎 ${data.dislikes}`;
        })
    }

    function dislike(post_id){
        fetch('{% url "blog:dislike" 0 %}'.replace('0', post_id))
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_like_' + post_id).innerText = `👍 ${data.likes}`;
            document.getElementById('btn_dislike_' + post_id).innerText = `👎 ${data.dislikes}`;
        })
    }

    {% for post in posts %}
        document.getElementById('btn_like_{{post.id}}').addEventListener('click', function(){
            like({{post.id}});
        });

        document.getElementById('btn_dislike_{{post.id}}').addEventListener('click', function(){
            dislike({{post.id}});
        });
    {% endfor %}
</script>
{% endblock %}

apps/blog/templates/blog/post.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}



{% block content %}
    

        <div class="mt-3 rounded-3 bg-body-tertiary p-4">
            <img src="{{post.image.url}}" class="img-fluid rounded-3" width="100%" alt="...">
            <h3>{{post.title}}</h3>
            <small class="text-muted">{{post.created_at}}</small>
            <small class="text-muted">{{post.author}}</small>
            <small class="text-muted">{{post.category}}</small>
            <div class="d-flex justify-content-between text-center">
                <h5><span class="badge ">👁️ {{post.views}}</span></h5>
                <h5><span class="badge ">🗨️ {{post.comments.count}}</span></h5>
                <h5><span class="btn btn-secondary" id="btn_like">👍 {{post.likes.count}}</span></h5>
                <h5><span class="btn btn-secondary" id="btn_dislike">👎 {{post.dislikes.count}}</span></h5>
            </div>
            <hr class="my-4">
            <p>{{post.content}}</p>
        </div>
        <div class="mt-3 rounded-3 bg-body-tertiary p-4">
            <h5>Коментарі</h5>
            🗨️ {{post.comments.count}}
            <hr class="mx-2">
            <form action="{% url 'blog:comment' post.id %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="comment" class="form-label">Ваш коментар</label>
                    <textarea class="form-control" id="comment" name="content" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Відправити</button>
            </form>
            <hr class="my-4">
            {% for comment in post.comments.all %}
                <div class="d-flex justify-content-between">

                    <div>
                        <h5>{{comment.author}}</h5>
                        <p>{{comment.content}}</p>
                        <button type="button" class="btn btn-secondary" onclick="like_comment({{comment.id}})" id="btn_like_comment_{{comment.id}}">❤️ {{comment.likes.count}}</button>
                         <button type="button" class="btn btn-secondary" onclick="dislike_comment({{comment.id}})" id="btn_dislike_comment_{{comment.id}}">💔 {{comment.dislikes.count}}</button>
                    </div>
                    <div>
                        <small class="text-muted text-end">{{comment.created_at}}</small>
                    </div>
                </div>
                <hr>
            {% endfor %}
        </div>


<script>
    document.getElementById('btn_like').addEventListener('click', function(){
        fetch('{% url "blog:like" post.id %}')
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_like').innerText = `👍 ${data.likes}`;
            document.getElementById('btn_dislike').innerText = `👎 ${data.dislikes}`;
        })
        .catch(error => console.log(error));
    });

    document.getElementById('btn_dislike').addEventListener('click', function(){
        fetch('{% url "blog:dislike" post.id %}')
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_dislike').innerText = `👎 ${data.dislikes}`;
            document.getElementById('btn_like').innerText = `👍 ${data.likes}`;
        })
        .catch(error => console.log(error));
    });

    function like_comment(comment_id){
        fetch('{% url "blog:like_comment" post.id 0 %}'.replace('0', comment_id))
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_like_comment_' + comment_id).innerText = `❤️ ${data.likes}`;
            document.getElementById('btn_dislike_comment_' + comment_id).innerText = `💔 ${data.dislikes}`;
        })
        .catch(error => console.log(error));
    }

    function dislike_comment(comment_id){
        fetch('{% url "blog:dislike_comment" post.id 0 %}'.replace('0', comment_id))
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_dislike_comment_' + comment_id).innerText = `💔 ${data.dislikes}`;
            document.getElementById('btn_like_comment_' + comment_id).innerText = `❤️ ${data.likes}`;
        })
        .catch(error => console.log(error));
    }
</script>
{% endblock %}