apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.posts, name='index'),
    path('<int:post_id>/', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/comment/', views.comment, name='comment'),
    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/dislike/', views.dislike, name='dislike'),
    path('<int:post_id>/comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    path('<int:post_id>/comment/<int:comment_id>/dislike/', views.like_comment, name='dislike_comment'),
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('<int:post_id>/redact/', views.redact_post, name='redact_post')
]

apps/members/urls.py
from django.urls import path
from .views import *

app_name = 'members'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    path('profile/', profile_view, name='profile'),
    ] 

cor/urls.py
from django.urls import path, include

"""
URL configuration for cor project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('members/', include('apps.members.urls', namespace='members')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include

"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('catalog/', include('apps.catalog.urls', namespace='catalog')),
    path('members/', include('apps.members.urls', namespace='members')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/members/models.py
from django.db import models

# Create your models here.

apps/members/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

apps/members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import random

from .forms import UserCreateForm
from apps.blog.forms import PostForm

# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Ви увійшли як {username}')
                return redirect('members:profile')
    else:
        form = AuthenticationForm()
    return render(request, 'members/login.html', {'form': form})


@login_required
def logout_view(request):
    logout(request)
    messages.info(request, 'Ви вийшли з системи')
    return redirect('members:login')


def signup_view(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.email = form.cleaned_data.get('email')
            user.save()
            login(request, user)
            messages.success(request, f'Ви успішно зареєструвалися як {user.username}')
            return redirect('members:profile')
    else:
        form = UserCreateForm()
    return render(request, 'members/signup.html', {'form': form})

@login_required
def profile_view(request):
    form_create_post = PostForm()
    context = {
        'form_create_post': form_create_post,
        # 'themeColor': getRandomColor()
    }
    
    return render(request, 'members/profile.html', context)

def getRandomColor():
    colors = ["#FF0000", "#800000", "#FFFF00", "#808000"]
    return f"background: {random.choice(colors)}"

apps/members/templates/members/login.html
{% extends 'base.html' %}

{% block title %}ЛОГІН{% endblock %}



{% block content %}

<div class="mt-4 rounded-3 bg-body-tertiary p-4">
        <h3 class="text-center">Логін</h3>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label">Ім'я користувача</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Пароль</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="submit" class="btn btn-primary">Увійти</button>
        </form>
</div>
{% endblock %}

apps/members/templates/members/profile.html
{% extends 'base.html' %}

{% block title %}Профіль{% endblock %}



{% block content %}

<div class="mt-4 rounded-3 bg-body-tertiary p-4">
        <h3 class="text-center">Профіль</h3>
        <p>Ім'я користувача: {{ user.username }}</p>
        <p>Ім'я: {{ user.first_name }}</p>
        <p>Прізвище: {{ user.last_name }}</p>
        <p>Електронна пошта: {{ user.email }}</p>
        <p>Дата реєстрації: {{ user.date_joined }}</p>
        <p>Дата останнього входу: {{ user.last_login }}</p>
</div>
<div class="mt-4 rounded-3 bg-body-tertiary p-4">
        <div class="text-center">
            <h3 class="text-center">Ваші пости</h3>
            <p class="text-center">Кількість постів: {{ user.posts.all.count }}</p>
        </div>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Створити пост
             </button>
        <hr class="my-4">
        <div class="row g-4">
            {% for post in user.posts.all %}
                <div class="col-4">
                    <div class="card">
                        <div class="card-header">
                            <div class="text-center">
                                <a href="{% url 'blog:redact_post' post.id %}" class="btn btn-sm" style="background-color: #4CAF50; color: #fff;">Редагувати</a>
                                <a href="{% url 'blog:delete_post' post.id %}" class="btn btn-sm" style="background-color: #FF0000; color: #FFFFFF;">Видалити</a>
                            </div>
                        </div>
                        <p href="{% url 'blog:post' post.id %}" class="text-decoration-none text-white">
                        <img src="{{post.image.url}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">@{{post.author}}</p>
                                <small class="text-muted">{{post.created_at|timesince}}</small>
                        </div>
                        </a>
                                <div class="card-footer">
                                        <div class="d-flex justify-content-between text-center">
                                        <h5><span class="badge ">👁️ {{post.views}}</span></h5>
                                        <h5><span class="badge ">🗨️ {{post.comments.count}}</span></h5>
                                        <h5><span class="badge ">👍 {{post.likes.count}}</span></h5>
                                        <h5><span class="badge ">👎 {{post.dislikes.count}}</span></h5>
                                        </div>
                                </div>
                        </div>
                </div>
                {% endfor %}


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Створити пост</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'blog:create' %}" method="post" enctype="multipart/form-data">
    
                <div class="modal-body">
                    {% csrf_token %}
                    {{ form_create_post }}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Створити</button>
                    
                </div>
            </form>
          </div>
        </div>
      </div>
</div>
</div>

<script>

    function ran_col() {
        const maxValue = 255;
        const cardHeaders = document.querySelectorAll("div.card-header");

        var currentColorValue = 0;

        var delta = Math.floor(maxValue / cardHeaders.length);q

        for (var i = 0; i < cardHeaders.length; i++) {
            currentColorValue += delta;
            if (currentColorValue >= maxValue) {
                currentColorValue = 0;
            }
            const rgb = `rgb(${currentColorValue}, ${currentColorValue}, ${currentColorValue})`;
            cardHeaders[i].style.background = rgb;
        }
    }

    window.onload = ran_col();
  </script>
{% endblock %}

apps/members/templates/members/signup.html
{% extends 'base.html' %}

{% block title %}ЛОГІН{% endblock %}



{% block content %}

<div class="mt-4 rounded-3 bg-body-tertiary p-4">
        <h3 class="text-center">Зареєструватися</h3>
        <form method="post">
            {% csrf_token %}

            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor %}
            {% endif %}
            
            {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}" required value="{{ field.value|default_if_none:'' }}">
                    <!-- {% for error in field.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %} -->
                </div>
            {% endfor %}
            <!-- <div class="mb-3">
                <label for="username" class="form-label">Ім'я користувача</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="mb-3">
                <label for="first_name" class="form-label">Ім'я</label>
                <input type="text" class="form-control" id="first_name" name="first_name" required>
            </div>
            <div class="mb-3">
                <label for="last_name" class="form-label">Прізвище</label>
                <input type="text" class="form-control" id="last_name" name="last_name" required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Електронна пошта</label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div class="mb-3">
                <label for="password1" class="form-label">Пароль</label>
                <input type="password" class="form-control" id="password1" name="password1" required>
            </div>
            <div class="mb-3">
                <label for="password2" class="form-label">Підтвердження паролю</label>
                <input type="password" class="form-control" id="password2" name="password2" required>
            </div> -->
            <button type="submit" class="btn btn-primary">Зареєструватися</button>
        </form>
</div>
{% endblock %}